Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [1]:
import pandas as pd

In [17]:
def rating_ (rating):
    if rating <= 2:
        return 'Низкий'
    elif 2 < rating <= 4:
        return 'Средний'
    elif rating >= 4.5:
        return 'Высокий'


movies = pd.read_csv('movies.csv')
rating = pd.read_csv('ratings.csv')
obshaya = rating.merge(movies, how = 'left', on='movieId')
obshaya['class'] = obshaya['rating'].apply(rating_)
obshaya.head(5)

,userId,movieId,rating,timestamp,title,genres,class
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,Средний
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,Средний
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,Средний
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,Низкий
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,Средний

Задание 2
Используем файл keywords.csv.
Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.
Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}
Результат классификации запишите в отдельный столбец region.

In [13]:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [15]:
def keyword_csv (keyword):
    for key, value in geo_data.items():
        if keyword in value:
            return key
    for value in geo_data.values():
        if keyword not in value:
            return 'undefained'


data = pd.read_csv('keywords.csv')
data['region'] = data['keyword'].apply(keyword_csv)
data.head()

         keyword     shows      region
0             вк  64292779  undefained
1  одноклассники  63810309  undefained
2          порно  41747114  undefained
3           ютуб  39995567  undefained
4      вконтакте  21014195  undefained

In [16]:
#ЧТО БЫ УБЕДИТЬСЯ ЧТО РАБОТАЕТ

region_filter = data[data['region'].isin(['Центр', 'Северо-Запад', 'Дальний Восток'])]
region_filter.head()

          keyword   shows          region
1259       москва  153050           Центр
5858  владивосток   43038  Дальний Восток
6075    ярославль   41720           Центр
8977     мурманск   29984    Северо-Запад
9084    хабаровск   29655  Дальний Восток